development:
  strategy: oauth
  oauth_consumer_key: "ag3MgBQxoWZw0HIphiSVJA"
  oauth_consumer_secret: "HHIihKj9lGcuMygoo8V3LtFbmIaMq4AeQ01hjO5yg"
  base_url: "http://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: "ag3MgBQxoWZw0HIphiSVJA"
  oauth_consumer_secret: "HHIihKj9lGcuMygoo8V3LtFbmIaMq4AeQ01hjO5yg"
  authorize_path: "/oauth/authenticate"  
  base_url: "http://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: "mYVpHP2cDefp9LHZj4NMw"
  oauth_consumer_secret: "tViTPLaqcUMKtWviTlecRI2NUMT94FCAjkwNjU6tJF4"
  authorize_path: "/oauth/authenticate"  
  base_url: "http://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
